version: '3.8'

services:
  server:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    container_name: server
